# Generated by Django 5.2.5 on 2025-12-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modulo3', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mesa', models.IntegerField(default=1)),
                ('cliente', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('URGENTE', 'Urgente'), ('CREADO', 'Creado'), ('EN_PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='CREADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('hora_listo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido Cocina',
                'verbose_name_plural': 'Pedidos Cocina',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
